---
title: "Example Plots"
author: "Kyle F. Butts"
date: "9/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gapminder)
library(sf)
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, prompt = FALSE, tidy = TRUE, comment = NA, message = FALSE, warning = FALSE)

library(tidyverse)
library(gapminder)

source("theme_kyle.R")
```

# Change over time

## Single line chart
```{r, tidy = FALSE, fig.cap = "Life expectancy in Argentina, 1952-2007 single line chart."}
df <- filter(gapminder, country == "Argentina") %>%
	mutate(year = as.Date(paste(year, "-01-01", sep = "", format = "%Y-%b-%d")))

ggplot(df, aes(x = year, y = lifeExp)) +
	geom_line(colour = "#fc6721", size = 1) +
	geom_point(colour = "#fc6721", size = 2) +
	scale_x_date(breaks = df$year, date_labels = "%Y") +
	scale_y_continuous(limits = c(0, 80)) +
	labs(
	title = "Life expectancy in Argentina, 1952-2007",
	subtitle = "A positive growth in years",
	caption = "Source: Gapminder.org  |  @traffordDataLab",
	x = "Year",
	y = "Age (years)"
	) +
	theme_kyle(title_pos = "center")
```

## Multiple line chart
```{r, tidy = FALSE, fig.cap = "Life expectancy in Argentina and Italy, 1952-2007 multple line chart."}
df <- filter(gapminder, country %in% c("Argentina", "Italy")) %>% 
	mutate(year = as.Date(paste(year, "-01-01", sep = "", format='%Y-%b-%d')))

ggplot(df, aes(x = year, y = gdpPercap, colour = country)) +
	geom_line(size = 1) +
	geom_point(size = 2) +
	scale_colour_manual(values = c("Argentina" = "#fc6721", "Italy" = "#E7B800")) + 
	scale_x_date(breaks = df$year, date_labels = "%Y") +
	scale_y_continuous(limits = c(0, 30000), labels = scales::dollar) +
	labs(
		title = "Life expectancy in Argentina and Italy",
		caption = "Source: Gapminder.org  |  @traffordDataLab",
		x = NULL,
		y = "GDP per capita ($)",
		colour = NULL
	) +
	theme_kyle(title_pos = "center")
```

## Bar chart (vertical)
```{r, tidy = FALSE, fig.cap = "GDP per capita in Egypt, 1952-2007 vertical bar chart."}
df <- filter(gapminder, country == "Egypt") %>% 
	mutate(year = as.Date(paste(year, "-01-01", sep = "", format='%Y-%b-%d')))

ggplot(df, aes(x = year, y = gdpPercap)) +
	geom_col(fill = "#fc6721", alpha = 0.8) +
	scale_x_date(breaks = df$year, date_labels = "%Y") +
	scale_y_continuous(expand = c(0, 0), labels = scales::dollar) + 
	labs(
		title = "GDP per capita in Egypt, 1952-2007", 
		caption = "Source: Gapminder.org  |  @traffordDataLab",
		x = NULL, 
		y = "GDP per capita ($)", 
		fill = NULL
	) + 
	theme_kyle(title_pos = "center") + 
	theme(panel.grid.major.x = element_blank())
```

## Stacked area chart
```{r, tidy = FALSE, fig.cap = "GDP per capita by country, 1952-2007 stacked area chart."}
df <- gapminder %>% 
	filter(country %in% c("France", "Germany", "Ireland", "Italy", "New Zealand")) %>% 
	mutate(year = as.Date(paste(year, "-01-01", sep = "", format='%Y-%b-%d')))

ggplot(df, aes(x = year, y = gdpPercap, fill = country)) +
	geom_area(color = "white") +
	scale_fill_paletteer_d("nord::aurora") + 
	scale_x_date(breaks = df$year, date_labels = "%Y") +
	scale_y_continuous(expand = c(0, 0), labels = scales::dollar) +
	labs(
		title = "GDP per capita by country, 1952-2007",
	   caption = "Source: Gapminder.org  |  @traffordDataLab",
	   x = NULL,
	   y = "GDP per capita ($)",
	   fill = NULL) +
	theme_kyle(title_pos = "center")
```

# Correlation

## Scatterplot
```{r, tidy = FALSE, fig.cap = "Life Expectancy and Income, 2007 scatterplot."}
ggplot(filter(gapminder, year == 2007), aes(x = gdpPercap, y = lifeExp)) +
	geom_point(colour = "#fc6721", fill = "white") +
	scale_x_log10(labels = scales::dollar) +
	labs(
		title = "Life Expectancy and Income, 2007",
		caption = "Source: Gapminder.org  |  @traffordDataLab",
		x = "GDP per capita ($)",
		y = "Age (years)"
	) +
	theme_kyle(title_pos = "center", slides = FALSE)
```

## Bubble chart

```{r, tidy = FALSE, fig.cap = "Life Expectancy and Income, 2007 bubble chart."}
ggplot(filter(gapminder, year == 2007), aes(x = gdpPercap, y = lifeExp)) +
	scale_x_log10(labels = scales::dollar) +
	geom_point(aes(size = pop, fill = continent), shape = 21, colour = "white", alpha = 0.6) +
	scale_fill_paletteer_d("nord::aurora") + 
	scale_size_continuous(range = c(1, 20)) +
	labs(
		title = "Life Expectancy and Income, 2007",
		caption = "Source: Gapminder.org  |  @traffordDataLab",
		x = "GDP per capita ($)",
		y = "Age (years)",
		fill = "Continent"
	) +
	guides(size = FALSE) +
	theme_kyle(title_pos = "center", slides = TRUE)
```


## Facet Wrap

```{r, tidy = FALSE, fig.cap = "Life Expectancy and Income, 2007 bubble chart."}
ggplot(
		gapminder %>% filter(year == 2007) %>% filter(continent %in% c("Americas", "Asia", "Europe")), 
		aes(x = gdpPercap, y = lifeExp)
	) +
	scale_x_log10(labels = scales::dollar) +
	geom_point(aes(size = pop, fill = continent), shape = 21, colour = "white", alpha = 0.6) +
	facet_wrap(~ continent) +
	scale_fill_paletteer_d("nord::aurora") + 
	scale_size_continuous(range = c(1, 20)) +
	labs(
		title = "Life expectancy and income, 2007",
		x = "GDP per capita ($)",
		y = "Age (years)",
		fill
	) +
	guides(size = FALSE) +
	theme_kyle(title_pos = "center") +
	theme(panel.grid.major.x = element_blank(),
	    legend.position = "bottom", 
	) + 
	theme(
		axis.text.x = element_text(angle = 30, hjust = 1),
		# panel.spacing = grid::unit(1, "lines")
	)
```


# Deviation


# Distribution

## Histogram
```{r, tidy = FALSE, fig.cap = "Life expectancy distribution, 2007 histogram."}
ggplot(filter(gapminder, year == 2007), aes(x = lifeExp)) +
  geom_histogram(binwidth = 1, fill = "#fc6721", colour = "white", alpha = 0.8) +
  scale_y_continuous(breaks = scales::pretty_breaks()) +
  labs(title = "Life expectancy distribution, 2007",
       caption = "Source: Gapminder.org  |  @traffordDataLab",
       x = "Age (years)",
       y = "") +
  theme_kyle(title_pos = "center")
  
```

## Density plot
```{r, tidy = FALSE, fig.cap = "Life expectancy distribution, 2007 density plot."}
ggplot(filter(gapminder, year == 2007), aes(x = lifeExp)) + 
  geom_density(aes(fill = continent), size = 0.1, alpha = 0.5) +
  labs(title = "",
       subtitle = "Life expectancy distribution, 2007",
       caption = "Source: Gapminder.org  |  @traffordDataLab",
       x = "Age (years)",
       y = "",
       fill = NULL) +
  theme_kyle(title_pos = "center") +
  theme(panel.grid.major.x = element_blank())
```


## Ridgeline plot
```{r, tidy = FALSE, fig.cap = "Life expectancy distribution, 2007 ridgeline plot."}
library(ggridges)
df <- gapminder %>% filter(year == 2007 & continent != "Oceania")
ggplot(df, aes(x = lifeExp, y = fct_rev(continent), fill = continent)) +
  geom_density_ridges(colour = "#bdbdbd", size = 0.5, alpha = 0.5) +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  scale_fill_brewer(palette = "Set2") +
  labs(title = "Life expectancy distribution, 2007",
       caption = "Source: Gapminder.org  |  @traffordDataLab",
       x = "Age (years)",
       y = "") +
  theme_kyle(title_pos = "center") +
  theme(panel.grid.major.x = element_blank(),
        legend.position = "none")
```

# Spatial

## Choropleth map
```{r, tidy = FALSE, fig.cap = "Life expectancy, 2007 choropleth map."}

nc <- st_read(system.file("shape/nc.shp", package="sf"))

ggplot(nc) + 
	geom_sf(aes(fill = BIR79)) + 
	coord_sf(datum = NA) +
	labs(
		title = "NC Births in 1979"
	) +
	theme_kyle(slides = FALSE, legend.position = "bottom") +
	scale_fill_gradientn(
		colours = brewer.pal(5, "Oranges"),
		name = "Number of Births",
		guide = guide_colourbar(
			direction = "horizontal",
			barheight = unit(2, units = "mm"),
			barwidth = unit(50, units = "mm"),
			title.position = 'top',
			title.hjust = 0.5,
			label.hjust = 0.5
		)
	) 

```



# Color Palettes

## Categorical
```{r}
ggplot(data = tibble(id = 1:6, xmin = id, xmax = id + 1, ymin = 0, ymax = 1)) + 
	geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = as.factor(id))) +
	scale_fill_manual(values = palette_kyle_categorical)
```

```{r}
ggplot(data = tibble(id = 1:6, xmin = id, xmax = id + 1, ymin = 0, ymax = 1)) + 
	geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = as.factor(id))) +
	scale_fill_manual(values = palette_kyle_scale)
```





